-- ============================================================
-- 32_stone_item_master.sql
-- Stone Item Master: table, trigger, lookup seeds
-- Menu MM_STONE_ITEMS already exists — no menu insert needed.
-- Run after 31_remove_variant_count_from_list.sql
-- ============================================================

BEGIN;

-- ══════════════════════════════════════════════════════════════
-- 1. STONE ITEM MASTER TABLE
-- ══════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS stone_item_master (
    id          SERIAL PRIMARY KEY,
    stn_code    VARCHAR(300) UNIQUE,        -- auto-generated by trigger from lookup codes
    stn_type    VARCHAR(100),
    stn_shape   VARCHAR(100),
    stn_quality VARCHAR(100),
    stn_color   VARCHAR(100),
    stn_size    VARCHAR(100),
    is_active   BOOLEAN   DEFAULT TRUE,
    created_by  INT,
    updated_by  INT,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_stone_item_code   ON stone_item_master(stn_code);
CREATE INDEX IF NOT EXISTS idx_stone_item_type   ON stone_item_master(stn_type);
CREATE INDEX IF NOT EXISTS idx_stone_item_active ON stone_item_master(is_active);

-- ══════════════════════════════════════════════════════════════
-- TRIGGER: auto-generate stn_code from lookup codes
-- Format: STN_TYPE-STN_SHAPE-QUALITY-COLOR-SIZE
-- ══════════════════════════════════════════════════════════════
CREATE OR REPLACE FUNCTION fn_stone_item_gen_code()
RETURNS TRIGGER AS $$
BEGIN
    NEW.stn_code := UPPER(CONCAT_WS('-',
        NULLIF(TRIM(NEW.stn_type),    ''),
        NULLIF(TRIM(NEW.stn_shape),   ''),
        NULLIF(TRIM(NEW.stn_quality), ''),
        NULLIF(TRIM(NEW.stn_color),   ''),
        NULLIF(TRIM(NEW.stn_size),    '')
    ));
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trg_stone_item_code
BEFORE INSERT OR UPDATE ON stone_item_master
FOR EACH ROW EXECUTE FUNCTION fn_stone_item_gen_code();

-- ══════════════════════════════════════════════════════════════
-- 2. LOOKUP SEEDS  (STN_SHAPE only — STONE_TYPE / QUALITY / COLOR / SIZE already in master_lookup)
-- ══════════════════════════════════════════════════════════════

-- Stone Shapes (STN_SHAPE)
INSERT INTO master_lookup (lookup_type, lookup_code, lookup_name, display_order, is_active)
VALUES
  ('STN_SHAPE', 'ROUND',    'Round',    1, TRUE),
  ('STN_SHAPE', 'OVAL',     'Oval',     2, TRUE),
  ('STN_SHAPE', 'PEAR',     'Pear',     3, TRUE),
  ('STN_SHAPE', 'MARQUISE', 'Marquise', 4, TRUE),
  ('STN_SHAPE', 'PRINCESS', 'Princess', 5, TRUE),
  ('STN_SHAPE', 'CUSHION',  'Cushion',  6, TRUE),
  ('STN_SHAPE', 'RADIANT',  'Radiant',  7, TRUE),
  ('STN_SHAPE', 'HEART',    'Heart',    8, TRUE),
  ('STN_SHAPE', 'ASSCHER',  'Asscher',  9, TRUE)
ON CONFLICT (lookup_type, lookup_code) DO NOTHING;

COMMIT;
