-- ============================================================
-- 33_component_item_master.sql
-- Component Item Master: table + auto-code trigger
-- Lookup seeds for METAL_TYPE / COMPONENT_TYPE / KARAT_COL /
-- PURITY / COMPONENT_NAME must be added via Lookup Master UI.
-- Run after 32_stone_item_master.sql
-- ============================================================

BEGIN;

-- ══════════════════════════════════════════════════════════════
-- 1. COMPONENT ITEM MASTER TABLE
-- ══════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS component_item_master (
    id               SERIAL PRIMARY KEY,
    comp_code        VARCHAR(500) UNIQUE,        -- auto-generated by trigger
    comp_metal_type  VARCHAR(100),
    comp_type        VARCHAR(100),
    comp_karat_color VARCHAR(100),
    comp_purity      VARCHAR(100),
    comp_name        VARCHAR(100),
    is_active        BOOLEAN   DEFAULT TRUE,
    created_by       INT,
    updated_by       INT,
    created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_comp_item_code   ON component_item_master(comp_code);
CREATE INDEX IF NOT EXISTS idx_comp_item_type   ON component_item_master(comp_type);
CREATE INDEX IF NOT EXISTS idx_comp_item_active ON component_item_master(is_active);

-- ══════════════════════════════════════════════════════════════
-- 2. TRIGGER: auto-generate comp_code from lookup codes
-- Format: METAL_TYPE-COMP_TYPE-KARAT_COL-PURITY-COMP_NAME
-- ══════════════════════════════════════════════════════════════
CREATE OR REPLACE FUNCTION fn_component_item_gen_code()
RETURNS TRIGGER AS $$
BEGIN
    NEW.comp_code := UPPER(CONCAT_WS('-',
        NULLIF(TRIM(NEW.comp_metal_type),  ''),
        NULLIF(TRIM(NEW.comp_type),        ''),
        NULLIF(TRIM(NEW.comp_karat_color), ''),
        NULLIF(TRIM(NEW.comp_purity),      ''),
        NULLIF(TRIM(NEW.comp_name),        '')
    ));
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trg_component_item_code
BEFORE INSERT OR UPDATE ON component_item_master
FOR EACH ROW EXECUTE FUNCTION fn_component_item_gen_code();

-- ══════════════════════════════════════════════════════════════
-- 3. LOOKUP SEEDS  (COMPONENT_TYPE sample data)
-- ══════════════════════════════════════════════════════════════
INSERT INTO master_lookup (lookup_type, lookup_code, lookup_name, display_order, is_active)
VALUES
  ('COMPONENT_TYPE', 'CASTING',   'Casting',    1, TRUE),
  ('COMPONENT_TYPE', 'STAMPING',  'Stamping',   2, TRUE)
ON CONFLICT (lookup_type, lookup_code) DO NOTHING;

COMMIT;
