-- production updated time: 2026-06-18 16:26:00
-- ============================================================
-- 48_all_forms_config_queries.sql  
-- Move all hardcoded SQL from stoneItem, componentItem,
-- lookup, supplierMaster, and customerMaster controllers
-- into project_config. Controllers become pure orchestrators.
-- ============================================================

BEGIN;

-- ══════════════════════════════════════════════════════════════
-- STONE ITEMS
-- ══════════════════════════════════════════════════════════════

INSERT INTO project_config (key_code, config_type, description, key_value) VALUES

('stone_item_list_select', 'query', 'Stone items list — SELECT + FROM (controller appends WHERE/ORDER/LIMIT)',
'SELECT id, stn_code, stn_type, stn_shape, stn_quality, stn_color, stn_size,
       is_active, created_at, updated_at
FROM   stone_item_master'),

('stone_item_list_count', 'query', 'Stone items list — COUNT + FROM (controller appends WHERE)',
'SELECT COUNT(*) AS total FROM stone_item_master'),

('stone_item_stats', 'query', 'Stone items active/inactive counts',
'SELECT
  SUM(CASE WHEN is_active = TRUE  THEN 1 ELSE 0 END) AS active,
  SUM(CASE WHEN is_active = FALSE THEN 1 ELSE 0 END) AS inactive
FROM stone_item_master'),

('stone_item_create', 'query', 'Insert new stone item — stn_code generated by DB trigger',
'INSERT INTO stone_item_master
  (stn_type, stn_shape, stn_quality, stn_color, stn_size,
   is_active, created_by, created_at, updated_at)
VALUES ($1,$2,$3,$4,$5,TRUE,$6,NOW(),NOW())
RETURNING id, stn_code'),

('stone_item_update', 'query', 'Update stone item — stn_code regenerated by DB trigger',
'UPDATE stone_item_master
SET stn_type = $1, stn_shape = $2, stn_quality = $3,
    stn_color = $4, stn_size = $5,
    updated_by = $6, updated_at = NOW()
WHERE id = $7
RETURNING id, stn_code'),

('stone_item_toggle', 'query', 'Toggle stone item active/inactive status',
'UPDATE stone_item_master
SET is_active = NOT is_active, updated_at = NOW()
WHERE id = $1
RETURNING id, is_active, stn_code'),

-- ══════════════════════════════════════════════════════════════
-- COMPONENT ITEMS
-- ══════════════════════════════════════════════════════════════

('comp_item_list_select', 'query', 'Component items list — SELECT + FROM (controller appends WHERE/ORDER/LIMIT)',
'SELECT id, comp_code, comp_metal_type, comp_type, comp_karat_color,
       comp_purity, comp_name, is_active, created_at, updated_at
FROM   component_item_master'),

('comp_item_list_count', 'query', 'Component items list — COUNT + FROM (controller appends WHERE)',
'SELECT COUNT(*) AS total FROM component_item_master'),

('comp_item_stats', 'query', 'Component items active/inactive counts',
'SELECT
  SUM(CASE WHEN is_active = TRUE  THEN 1 ELSE 0 END) AS active,
  SUM(CASE WHEN is_active = FALSE THEN 1 ELSE 0 END) AS inactive
FROM component_item_master'),

('comp_item_create', 'query', 'Insert new component item — comp_code generated by DB trigger',
'INSERT INTO component_item_master
  (comp_metal_type, comp_type, comp_karat_color, comp_purity, comp_name,
   is_active, created_by, created_at, updated_at)
VALUES ($1,$2,$3,$4,$5,TRUE,$6,NOW(),NOW())
RETURNING id, comp_code'),

('comp_item_update', 'query', 'Update component item — comp_code regenerated by DB trigger',
'UPDATE component_item_master
SET comp_metal_type = $1, comp_type = $2, comp_karat_color = $3,
    comp_purity = $4, comp_name = $5,
    updated_by = $6, updated_at = NOW()
WHERE id = $7
RETURNING id, comp_code'),

('comp_item_toggle', 'query', 'Toggle component item active/inactive status',
'UPDATE component_item_master
SET is_active = NOT is_active, updated_at = NOW()
WHERE id = $1
RETURNING id, is_active, comp_code'),

-- ══════════════════════════════════════════════════════════════
-- LOOKUP MASTER
-- ══════════════════════════════════════════════════════════════

('lookup_list_select', 'query', 'Lookup master list — SELECT + FROM (controller appends WHERE/ORDER/LIMIT)',
'SELECT id, lookup_type, lookup_code, lookup_name, lookup_value,
       display_order, parent_code, is_active, created_at, updated_at
FROM   master_lookup'),

('lookup_list_count', 'query', 'Lookup master list — COUNT + FROM (controller appends WHERE)',
'SELECT COUNT(*) AS total FROM master_lookup'),

('lookup_stats', 'query', 'Lookup master active/inactive counts',
'SELECT
  SUM(CASE WHEN is_active = TRUE  THEN 1 ELSE 0 END) AS active,
  SUM(CASE WHEN is_active = FALSE THEN 1 ELSE 0 END) AS inactive
FROM master_lookup'),

('lookup_types', 'query', 'Distinct lookup types for filter dropdown',
'SELECT DISTINCT lookup_type FROM master_lookup ORDER BY lookup_type'),

('lookup_dup_check', 'query', 'Check for duplicate lookup type+code before insert',
'SELECT id FROM master_lookup WHERE lookup_type = $1 AND lookup_code = $2'),

('lookup_create', 'query', 'Insert new lookup entry',
'INSERT INTO master_lookup
  (lookup_type, lookup_code, lookup_name, lookup_value,
   display_order, parent_code, updated_at)
VALUES ($1,$2,$3,$4,$5,$6,NOW())
RETURNING id'),

('lookup_update', 'query', 'Update lookup name, value, order, parent',
'UPDATE master_lookup
SET lookup_name = $1, lookup_value = $2, display_order = $3,
    parent_code = $4, updated_at = NOW()
WHERE id = $5
RETURNING id'),

('lookup_toggle', 'query', 'Toggle lookup active/inactive status',
'UPDATE master_lookup
SET is_active = NOT is_active, updated_at = NOW()
WHERE id = $1
RETURNING id, is_active, lookup_type, lookup_code'),

-- ══════════════════════════════════════════════════════════════
-- SUPPLIER MASTER
-- ══════════════════════════════════════════════════════════════

('supplier_list_select', 'query', 'Supplier list — SELECT + FROM (controller appends WHERE/ORDER/LIMIT)',
'SELECT sm.id, sm.vendor_code, sm.vendor_company_name, sm.bus_relationship,
       sm.country_code, sm.pan_card, sm.organization_type, sm.vendor_type,
       sm.is_msme_reg, sm.is_active, sm.created_at, sm.updated_at
FROM   supplier_master sm'),

('supplier_list_count', 'query', 'Supplier list — COUNT + FROM (controller appends WHERE)',
'SELECT COUNT(*) AS total FROM supplier_master sm'),

('supplier_stats', 'query', 'Supplier active/inactive counts',
'SELECT
  SUM(CASE WHEN is_active THEN 1 ELSE 0 END)     AS active,
  SUM(CASE WHEN NOT is_active THEN 1 ELSE 0 END) AS inactive
FROM supplier_master'),

('supplier_get_main', 'query', 'Get supplier main row by id',
'SELECT * FROM supplier_master WHERE id = $1'),

('supplier_get_contacts', 'query', 'Get supplier contacts by supplier_id',
'SELECT * FROM supplier_contact_info WHERE supplier_id = $1 ORDER BY id'),

('supplier_get_addresses', 'query', 'Get supplier addresses by supplier_id',
'SELECT * FROM supplier_address_info WHERE supplier_id = $1 ORDER BY id'),

('supplier_get_banks', 'query', 'Get supplier bank details by supplier_id',
'SELECT * FROM supplier_bank_detail WHERE supplier_id = $1 ORDER BY id'),

('supplier_create', 'query', 'Insert new supplier main row — returns id and vendor_code',
'INSERT INTO supplier_master
  (vendor_company_name, bus_relationship, country_code, pan_card,
   organization_type, vendor_type, is_msme_reg, vendor_url,
   gstin_uin_number, place_of_supply, msme_udyam_reg_number, gst_treatment,
   is_active, created_by, created_at, updated_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,TRUE,$13,NOW(),NOW())
RETURNING id, vendor_code'),

('supplier_update', 'query', 'Update supplier main row',
'UPDATE supplier_master SET
  vendor_company_name = $1, bus_relationship = $2, country_code = $3, pan_card = $4,
  organization_type = $5, vendor_type = $6, is_msme_reg = $7, vendor_url = $8,
  gstin_uin_number = $9, place_of_supply = $10, msme_udyam_reg_number = $11,
  gst_treatment = $12, updated_by = $13, updated_at = NOW()
WHERE id = $14'),

('supplier_contact_delete', 'query', 'Delete all contacts for a supplier',
'DELETE FROM supplier_contact_info WHERE supplier_id = $1'),

('supplier_address_delete', 'query', 'Delete all addresses for a supplier',
'DELETE FROM supplier_address_info WHERE supplier_id = $1'),

('supplier_bank_delete', 'query', 'Delete all bank details for a supplier',
'DELETE FROM supplier_bank_detail WHERE supplier_id = $1'),

('supplier_contact_insert', 'query', 'Insert one supplier contact row (controller loops)',
'INSERT INTO supplier_contact_info
  (supplier_id, cont_first_name, cont_last_name, cont_email, cont_job_title,
   cont_country_code, cont_mobile, cont_is_admin, cont_is_supplier_portal,
   created_at, updated_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,NOW(),NOW())'),

('supplier_address_insert', 'query', 'Insert one supplier address row (controller loops)',
'INSERT INTO supplier_address_info
  (supplier_id, adrs_name, adrs_country_code, adrs_1, adrs_2, adrs_3,
   adrs_city_name, adrs_state_code, adrs_pincode, adrs_email,
   adrs_phone_number_country_code, adrs_phone_number, adrs_extension,
   created_at, updated_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,NOW(),NOW())'),

('supplier_bank_insert', 'query', 'Insert one supplier bank detail row (controller loops)',
'INSERT INTO supplier_bank_detail
  (supplier_id, bank_country_code, bank_name, bank_branch_name,
   bank_account_number, bank_account_holder, bank_account_type,
   bank_account_currency_code, created_at, updated_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,NOW(),NOW())'),

('supplier_doc_update', 'query', 'Update supplier upload_doc JSON after file save',
'UPDATE supplier_master SET upload_doc = $1 WHERE id = $2'),

('supplier_toggle', 'query', 'Toggle supplier active/inactive status',
'UPDATE supplier_master
SET is_active = NOT is_active, updated_at = NOW()
WHERE id = $1
RETURNING id, is_active, vendor_code, vendor_company_name'),

-- ══════════════════════════════════════════════════════════════
-- CUSTOMER MASTER
-- ══════════════════════════════════════════════════════════════

('customer_list_select', 'query', 'Customer list — SELECT + FROM (controller appends WHERE/ORDER/LIMIT)',
'SELECT cm.id, cm.customer_code, cm.customer_name, cm.customer_company_name,
       cm.customer_display_name, cm.bus_relationship, cm.country_code,
       cm.pan_card, cm.organization_type, cm.customer_type,
       cm.is_active, cm.created_at, cm.updated_at
FROM   customer_master cm'),

('customer_list_count', 'query', 'Customer list — COUNT + FROM (controller appends WHERE)',
'SELECT COUNT(*) AS total FROM customer_master cm'),

('customer_stats', 'query', 'Customer active/inactive counts',
'SELECT
  SUM(CASE WHEN is_active THEN 1 ELSE 0 END)     AS active,
  SUM(CASE WHEN NOT is_active THEN 1 ELSE 0 END) AS inactive
FROM customer_master'),

('customer_get_main', 'query', 'Get customer main row by id',
'SELECT * FROM customer_master WHERE id = $1'),

('customer_get_contacts', 'query', 'Get customer contacts by customer_id',
'SELECT * FROM customer_contact_info WHERE customer_id = $1 ORDER BY id'),

('customer_get_addresses', 'query', 'Get customer addresses by customer_id',
'SELECT * FROM customer_address_info WHERE customer_id = $1 ORDER BY id'),

('customer_create', 'query', 'Insert new customer main row — returns id and customer_code',
'INSERT INTO customer_master
  (customer_name, customer_company_name, customer_display_name,
   bus_relationship, country_code, pan_card, organization_type,
   customer_type, is_msme_reg, website_url,
   tax_payer_type, gstin_status, gstin_uin_number,
   place_of_supply, gst_treatment,
   credit_limit_by_value, credit_limit_by_grams, payment_terms,
   is_active, created_by, created_at, updated_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,TRUE,$19,NOW(),NOW())
RETURNING id, customer_code'),

('customer_update', 'query', 'Update customer main row',
'UPDATE customer_master SET
  customer_name = $1, customer_company_name = $2, customer_display_name = $3,
  bus_relationship = $4, country_code = $5, pan_card = $6,
  organization_type = $7, customer_type = $8, is_msme_reg = $9, website_url = $10,
  tax_payer_type = $11, gstin_status = $12, gstin_uin_number = $13,
  place_of_supply = $14, gst_treatment = $15,
  credit_limit_by_value = $16, credit_limit_by_grams = $17, payment_terms = $18,
  updated_by = $19, updated_at = NOW()
WHERE id = $20'),

('customer_contact_delete', 'query', 'Delete all contacts for a customer',
'DELETE FROM customer_contact_info WHERE customer_id = $1'),

('customer_address_delete', 'query', 'Delete all addresses for a customer',
'DELETE FROM customer_address_info WHERE customer_id = $1'),

('customer_contact_insert', 'query', 'Insert one customer contact row (controller loops)',
'INSERT INTO customer_contact_info
  (customer_id, cont_first_name, cont_last_name, cont_email, cont_job_title,
   cont_country_code, cont_mobile, cont_is_admin, created_at, updated_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,NOW(),NOW())'),

('customer_address_insert', 'query', 'Insert one customer address row (controller loops)',
'INSERT INTO customer_address_info
  (customer_id, adrs_name, adrs_country_code, adrs_1, adrs_2, adrs_3,
   adrs_city_name, adrs_state_code, adrs_pincode, adrs_email,
   adrs_phone_number_country_code, adrs_phone_number, adrs_extension,
   created_at, updated_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,NOW(),NOW())'),

('customer_doc_update', 'query', 'Update customer upload_doc JSON after file save',
'UPDATE customer_master SET upload_doc = $1 WHERE id = $2'),

('customer_toggle', 'query', 'Toggle customer active/inactive status',
'UPDATE customer_master
SET is_active = NOT is_active, updated_at = NOW()
WHERE id = $1
RETURNING id, is_active, customer_code, customer_company_name');

COMMIT;
