-- ============================================================
-- 64_component_master.sql
-- New Component Master table (separate from old component_item_master
-- which was renamed to metal_master in script 62)
--
-- Component Code format: {COMP_TYPE}-{COMP_NAME}-{COMP_DESC}-NNN
-- Example: RB-SP-SP-001
-- NNN = 3-digit sequential number from dedicated sequence.
-- Code is generated on INSERT only; never changes after creation.
-- Run after 63_metal_master_menu.sql
-- ============================================================

BEGIN;

-- ══════════════════════════════════════════════════════════════
-- 1. SEQUENCE for code numbering (001, 002, ...)
-- ══════════════════════════════════════════════════════════════
CREATE SEQUENCE IF NOT EXISTS seq_component_code START 1 INCREMENT 1;

-- ══════════════════════════════════════════════════════════════
-- 2. COMPONENT MASTER TABLE
-- ══════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS component_master (
    id                  SERIAL PRIMARY KEY,
    component_code      VARCHAR(500) UNIQUE,
    component_type      VARCHAR(100),
    component_name      VARCHAR(100),
    component_desc      VARCHAR(100),
    is_active           BOOLEAN   DEFAULT TRUE,
    deactivation_reason VARCHAR(500),
    deactivated_at      TIMESTAMP,
    created_by          INT,
    updated_by          INT,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_comp_master_code   ON component_master(component_code);
CREATE INDEX IF NOT EXISTS idx_comp_master_type   ON component_master(component_type);
CREATE INDEX IF NOT EXISTS idx_comp_master_active ON component_master(is_active);

-- ══════════════════════════════════════════════════════════════
-- 3. TRIGGER — auto-generate component_code on INSERT only
--    Format: TYPE-NAME-DESC-NNN  (NNN = zero-padded sequence)
--    Code never changes after creation (trigger skips UPDATE).
-- ══════════════════════════════════════════════════════════════
CREATE OR REPLACE FUNCTION fn_component_master_gen_code()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.component_code := UPPER(CONCAT_WS('-',
            NULLIF(TRIM(NEW.component_type), ''),
            NULLIF(TRIM(NEW.component_name), ''),
            NULLIF(TRIM(NEW.component_desc), ''),
            LPAD(nextval('seq_component_code')::TEXT, 3, '0')
        ));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trg_component_master_code
BEFORE INSERT ON component_master
FOR EACH ROW EXECUTE FUNCTION fn_component_master_gen_code();

-- ══════════════════════════════════════════════════════════════
-- 4. LOOKUP SEED — COMPONENT_DESC (1 sample record as requested)
-- ══════════════════════════════════════════════════════════════
INSERT INTO master_lookup (lookup_type, lookup_code, lookup_name, display_order, is_active)
VALUES ('COMPONENT_DESC', 'SP', 'Spring', 1, TRUE)
ON CONFLICT (lookup_type, lookup_code) DO NOTHING;

-- ══════════════════════════════════════════════════════════════
-- 5. PROJECT CONFIG QUERIES
-- ══════════════════════════════════════════════════════════════
INSERT INTO project_config (key_code, config_type, description, key_value) VALUES

('comp_master_list_select', 'query',
 'Component master list — SELECT + FROM (controller appends WHERE/ORDER/LIMIT)',
 'SELECT id, component_code, component_type, component_name, component_desc,
        is_active, created_at, updated_at
 FROM   component_master'),

('comp_master_list_count', 'query',
 'Component master list — COUNT + FROM (controller appends WHERE)',
 'SELECT COUNT(*) AS total FROM component_master'),

('comp_master_stats', 'query',
 'Component master active/inactive counts',
 'SELECT
   SUM(CASE WHEN is_active = TRUE  THEN 1 ELSE 0 END) AS active,
   SUM(CASE WHEN is_active = FALSE THEN 1 ELSE 0 END) AS inactive
 FROM component_master'),

('comp_master_create', 'query',
 'Insert new component — component_code auto-generated by trigger',
 'INSERT INTO component_master
   (component_type, component_name, component_desc,
    is_active, created_by, created_at, updated_at)
 VALUES ($1,$2,$3,TRUE,$4,NOW(),NOW())
 RETURNING id, component_code'),

('comp_master_update', 'query',
 'Update component fields — component_code is NOT regenerated on update',
 'UPDATE component_master
 SET component_type = $1,
     component_name = $2,
     component_desc = $3,
     updated_by     = $4,
     updated_at     = NOW()
 WHERE id = $5
 RETURNING id, component_code'),

('comp_master_toggle', 'query',
 'Toggle component active/inactive status',
 'UPDATE component_master
 SET is_active           = NOT is_active,
     deactivation_reason = CASE WHEN is_active THEN $2 ELSE NULL END,
     deactivated_at      = CASE WHEN is_active THEN NOW() ELSE NULL END,
     updated_at          = NOW()
 WHERE id = $1
 RETURNING id, is_active, component_code')

ON CONFLICT (key_code) DO NOTHING;

COMMIT;
