-- ============================================================
-- 77_stone_item_std_cts.sql
-- Add std_cts (Standard Carats) column to stone_item_master.
-- Updates project_config queries to include the new column.
-- Run after 76_finding_master.sql
-- ============================================================

BEGIN;

-- ── 1. Add column ─────────────────────────────────────────────
ALTER TABLE stone_item_master
  ADD COLUMN IF NOT EXISTS std_cts NUMERIC(12,4);

-- ── 2. Update list SELECT to return std_cts ───────────────────
UPDATE project_config SET
  key_value =
'SELECT id, stn_code, stn_type, stn_shape, stn_quality, stn_color, stn_size,
       std_cts, is_active, created_at, updated_at
FROM   stone_item_master',
  description = 'Stone items list — SELECT + FROM (controller appends WHERE/ORDER/LIMIT)'
WHERE key_code = 'stone_item_list_select';

-- ── 3. Update INSERT: add std_cts as $6, shift created_by to $7
UPDATE project_config SET
  key_value =
'INSERT INTO stone_item_master
  (stn_type, stn_shape, stn_quality, stn_color, stn_size,
   std_cts, is_active, created_by, created_at, updated_at)
VALUES ($1,$2,$3,$4,$5,$6,TRUE,$7,NOW(),NOW())
RETURNING id, stn_code',
  description = 'Insert new stone item — stn_code generated by DB trigger'
WHERE key_code = 'stone_item_create';

-- ── 4. Update UPDATE: add std_cts as $6, shift updated_by to $7, id to $8
UPDATE project_config SET
  key_value =
'UPDATE stone_item_master
SET stn_type = $1, stn_shape = $2, stn_quality = $3,
    stn_color = $4, stn_size = $5, std_cts = $6,
    updated_by = $7, updated_at = NOW()
WHERE id = $8
RETURNING id, stn_code',
  description = 'Update stone item — stn_code regenerated by DB trigger'
WHERE key_code = 'stone_item_update';

COMMIT;
