// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { existsSync } from "node:fs";
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

// The running API loads .env.local (see the dev script in package.json). Load the
// same file here so the CLI can never migrate a different database than the one
// the app talks to. Falls back to .env, then to the ambient environment where no
// file exists at all (Docker, CI).
for (const file of [".env.local", ".env"]) {
  if (existsSync(file)) {
    dotenv.config({ path: file });
    break;
  }
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
